---
- name: Create user and group on servers
  hosts: all
  become: true
  handlers:
    - name: restart-sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

  tasks:
    - name: create group
      ansible.builtin.group: 
        name: jboss
        state: present
    - name: create user
      ansible.builtin.user: 
        name: jboss
        state: present
        shell: /bin/bash
        create_home: true
        home: /home/jboss
    - name: provide sudo privileges without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/jboss
        state: present
        create: true
        mode: 0440
        line: "%jboss ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
    - name: Enable password auth
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#   PasswordAuthentication yes"
        line: "PasswordAuthentication yes"
    - name: Enable root login
      ansible.builtin.lineine:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin yes"
      notify: restart-sshd