cpu_script_path: "/jboss/cpucheck.sh"
cpu_cron_name: "Run cpu script"
cpu_cron_minute: "*/2"
cpu_cron_hour: "*"
cpu_cron_day: "*"
cpu_cron_month: "*"
cpu_cron_weekday: "*"
cpu_cron_user: "root"
